### PR TITLE
moderation/notifications/filter: fixing wrongly shown notifications w…

### LINKED ISSUE #147: Moderation Dashboard: Filtering (All, Pending, Archived) not immediate!
**URL:** local/dev
**user:** moderator
**expected behaviour:** Changing filter from "All" to "Pending" or "Archived" showing immediately the right content
**behaviour:**  Changing leads to -sometimes- showing wrong notifications. Being corrected after 1-2 seconds.
**important screensize:** any
**device & browser:** tested in chrome
**Comment/Question:** It filters correctly, but there is a glitch of ~1 sec. where it can show wrong notifications.

Screenshot?

### PR DESCRIPTION
**Pull request by khamui**
…hen filtering.

added a frontend filtering and making sure loading state changes after fetching

closes #147

### CODE REVIEW

File: apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationNotificationList.jsx [hunk 1]
```diff
@@ -44,7 +44,10 @@ export default class ModerationNotificationList extends Component {
     const userFetch = await fetch(userUrl)
     const userNotifications = await userFetch.json()
 
-    this.setState({ notifications: [...aiNotifications, ...userNotifications], isLoaded: true })
+    this.setState(
+      { notifications: [...aiNotifications, ...userNotifications] },
+      () => this.setState({ isLoaded: true })
```
Comment (khamui) [inline apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationNotificationList.jsx:49]: this might look weird at first sight, i just read in the docs that you can add a callback as a second argument, which waits for the first argument (setting the notifications) to be finished. does that make sense?

Comment (sabinammm) [reply apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationNotificationList.jsx:49]: It's still happening (but only every 20-30th time or so I switch). Also, it doesn't change after a few seconds.
image

 If I reload, it switches the filter to "All" and shows all notifications.

Comment (phillimorland) [reply apps/userdashboard/assets/js/a4_candy_userdashboard/ModerationNotificationList.jsx:49]: @sabinammm reload behaviour is expected else we would have to set cookies

**Review by phillimorland — APPROVED** [review]
@khamui just realised I can't reproduce this issue either on dev or locally on main (which is interesting) but code looks good so will merge and we can see how we get on
